### ISSUE TITLE
Plugin Enforced = yes

### ISSUE THREAD

**Issue by jayamin-10** [DonutsNL/phpsaml2#1]
@DonutsNL Hey, i hope you're doing well. I just needed an information about plugin enfored option. When we enfore the plugin we no longer have the option to connect to GLPI directly. Is there anyway that we can still access the GLPI login page through another URL ?
I can give you an exemple like if we enforce the plugin glpi should be accessible through www.exemple-glpi.com/index.php and the  direct connection page would be on url www.exemple-glpi.com/index.php?noAUTO=1

**Comment by DonutsNL** [comment]
Currently there is no way to bypass it. We have been discussing  the option to configure a specific key to allow bypassing the saml auth. This also to enable troubleshooting of the saml auth isnt working but is enforced.

**Comment by DonutsNL** [comment]
Maybe ill have a go at it after my vacation 😉

**Comment by jayamin-10** [comment]
> Currently there is no way to bypass it. We have been discussing the option to configure a specific key to allow bypassing the saml auth. This also to enable troubleshooting if the saml auth isnt working but is enforced.

Or is it not possible to have the GLPI login page on another url ? Enjoy your holiday :)

**Comment by ChrisGralike** [comment]
Not as far as i am aware. I have not seen any support for fancy URLs and as far as i am aware does not implement a router. There is some routing logic, but its mostly very specific and functional in nature. For instance redirect page back to home using a redirect.

**Comment by rducloie** [comment]
Hi all ! I completely agree with jayamin-10.
It would be great if we could have a URL that bypasses the SAML login.
Sometimes I want to give access to GLPI to people outside my company, who do not exist in my Azure AD tenant.
Thank you very much if you think about it :)

**Comment by DonutsNL** [comment]
Hi @rducloie and @jayamin-10 
I added some logic to the https://github.com/DonutsNL/phpsaml repository. If you use this version you should be able to add "?NOSSO=1" to the URL that should now bypass the enforce option.  i.e. https://my.glpi.com/?NOSSO=1

Let me know if this works for you guys.
Cheers,

**Comment by rducloie** [comment]
Hi @DonutsNL !
Thank you for your quick feedback!
By adding "?NOSSO=1", I access the login page but when I click on "Login", I am automatically redirected to O365.

**Comment by DonutsNL** [comment]
apparently it is auto closing these if I mention the issue in a repository. Anywayz, i added a session var that should prevent the enforce from triggering once you tried a manual logon. Please give it another shot. I didnt fully test it (yet).

**Comment by ChrisGralike** [comment]
Hi @rducloie  and @jayamin-10  
please try the latest version and see if this works for you guys. Please let me know.

**Comment by jayamin-10** [comment]
Hi @ChrisGralike  i downloaded this version https://github.com/DonutsNL/phpsaml. and tried with ?NOSSO=1. It redirects automatically to O365 page. it didn't work for me.

**Comment by jayamin-10** [comment]
Hi, @ChrisGralike, i hope you're doing well. I tried the new version https://github.com/DonutsNL/phpsaml. ?NOSSO=1 doesn't work. It brings us back to O365 login page.

**Comment by DonutsNL** [comment]
Hi @jayamin-10, @rducloie 

As it turns out that GLPI is actively cleaning the $_SESSION vars. Values stored are not persistent. So i adopted the glpi cache manager instead and altered the logic. I tested various scenarios that work correctly in my test environment. Please download the latest version and give it another shot.

make sure to use `?nosso=1` uri to bypass the enforce option. Clicking the SSO button should restore the default behaviour for that session.

I am not sure the cache is cleaned by GLPI in time. This feature might clutter the glpi cache storage over time because there is no way to tell if a session went away. This is usually managed by the PHP session manager. Let me know if this works for you guys.

**Comment by rducloie** [comment]
Hi @DonutsNL 
I just tried it myself and it works perfectly, thank you very much from France!
Just one note: when connecting, a page is displayed very briefly with all the user's LDAP information.
I would like to post a screenshot but there is a lot of personal information...

**Comment by DonutsNL** [comment]
thats after the idp redirect back to glpi (acs.php)?

**Comment by DonutsNL** [comment]
You might use `fiddler` to record the session and jshare the http header information of the page showing the details without sharing the body. This should be enough allow me to find the source of this. Im curious where this is triggered, never saw this myself.
