### ISSUE TITLE
 Warning: plugin_version_phpsaml2 method must be defined! in html/src/Plugin.php on line 1794

### ISSUE THREAD

**Issue by ftoledo** [DonutsNL/phpsaml2#2]
Hello, how is the status of the code of this plugin? can. I see that you still have methods with another name in setup.php and hook.php

thanks!!!

**Comment by DonutsNL** [comment]
I was focussed on ticketfilter the past few months. I hope to find some time in december to start working on this plugin. It still needs alot of work (all help is welcoem) and I am also trying to maintain the original phpsaml as well as i can in derriks absence.

**Comment by ChrisGralike** [comment]
Im currently focussing again on writing phpsaml2. Ill close this issue because i fixed the psr4 autoloader issues ;-)
